image: ubuntu

environment:
  SITE_REPO_TOKEN: 
    secure: 9J4+3PqRqzTDiC280JthRE4EVP8YqK67eEDJmyD+2s+j8H/R5TyrJJJNnpOejxCH

-
  branches:
    only:
      - master
  environment:
    SITE_REPO: https://github.com/jogosdaqui/jogosdaqui.github.io.git
-
  environment:
    SITE_REPO: https://github.com/jogosdaqui/jogosdaqui.github.io-staging.git

install:
- sh: sudo apt-get update
- sh: sudo apt-get -y install curl
- sh: \curl -L https://get.rvm.io | bash -s stable --ruby
- sh: rvm get stable --autolibs=enable
- sh: rvm install ruby
- sh: gem install jekyll bundler

build_script:
- sh: bundle install
- sh: git config --global credential.helper "store --file ~/.git-credentials"
- ps: git config --global user.email $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL
- ps: git config --global user.name $env:APPVEYOR_REPO_COMMIT_AUTHOR
- ps: Add-Content "~/.git-credentials" "https://$($env:SITE_REPO_TOKEN):x-oauth-basic@github.com`n"
- ps: git clone $env:SITE_REPO _site
- sh: bundle exec jekyll build
- sh: cd _site
- sh: echo Last update = `date` > info.html
- sh: git add .
- ps: git commit -m "$($env:APPVEYOR_REPO_COMMIT_MESSAGE)"
- sh: git push