image: ubuntu
  
install:
- sh: sudo apt-get update
- sh: sudo apt-get -y install curl
- sh: \curl -L https://get.rvm.io | bash -s stable --ruby
- sh: rvm get stable --autolibs=enable
- sh: rvm install ruby
- sh: gem install jekyll bundler

build_script:
- sh: bundle install
- git config --global credential.helper store
- git config --global user.email %APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL%
- git config --global user.name %APPVEYOR_REPO_COMMIT_AUTHOR%
- sh: git clone https://github.com/jogosdaqui/jogosdaqui.github.io.git _site
- sh: bundle exec jekyll build
- sh: cd _site
- git add .
- git commit -m "%APPVEYOR_REPO_COMMIT_MESSAGE%"
- git push