image: ubuntu
  
install:
- sh: sudo apt-get update
- sh: sudo apt-get -y install curl
- sh: sudo curl -L https://get.rvm.io | bash -s stable --ruby
- sh: sudo rvm get stable --autolibs=enable
- sh: sudo rvm install ruby
- sh: sudo gem install jekyll bundler

build_script:
- sh: bundle exec jekyll build

artifacts:
  - path: _site/** 
    name: Generated jogosdaqui.gitub.io
  - path: /home/appveyor/.rvm/log/**/*.log
    name: logs


    