image: ubuntu
  
install:
- sh: sudo apt-get update
- sh: sudo apt-get install ruby-full
- sh: sudo gem install jekyll
- sh: jekyll -v

build_script:
- sh: bundle exec jekyll build

artifacts:
  - path: _site/** 
    name: Generated jogosdaqui.gitub.io