image: ubuntu
  
install:
- sh: sudo apt-get update
- sh: sudo apt-get -y install ruby2.5.3
- sh: sudo gem install jekyll

build_script:
- sh: ls 
- sh: bundle install  
- sh: bundle exec jekyll build

artifacts:
  - path: _site/** 
    name: jogosdaqui.gitub.io.zip